#!/bin/mksh

#bspc monitor --reset-desktops I II III IV V VI VII VIII IX X
bspc monitor --reset-desktops I II III IV V VI VII

#++++++++++#
# Paddings #
#++++++++++#
for pos in top botton right left; do
    bspc config "$pos"_padding    2
    bspc config "$pos"_monocle_padding    0
done

#++++++++++#
#  Colors  #
#++++++++++#
# color for a focused window of a focused monitor
bspc config focused_border_color    "#35C9BD"
# color for the preselected region
bspc config presel_feedback_color   "#35C9BD"
# color for an unfocused window
bspc config normal_border_color     "#6234C5"
# color for a focused window of an unfocused monitor
bspc config active_border_color     "#C16033"

#+++++++++++#
# Behaviors #
#+++++++++++#
bspc config border_width            1
bspc config window_gap		        5
bspc config split_ratio             0.50
bspc config automatic_scheme        spiral
bspc config single_monocle          true
bspc config gapless_monocle         true
bspc config borderless_monocle      true
bspc config pointer_follows_focus   true
bspc config pointer_follows_monitor true
bspc config initial_polarity        first_child
#bspc config initial_polarity       second_child

#++++++++++#
# Desktops #
#++++++++++#
#bspc desktop '^3' --layout monocle
#bspc desktop '^7' --layout monocle

#++++++++++#
#  Rules   #
#++++++++++#
bspc rule --remove "*"
bspc rule --add netsurf \
    desktop='^3' state=fullscreen
bspc rule --add Zathura	\
    desktop='IV' --one-shot follow=on focus=on state=fullscreen
bspc rule --add Conky \
    sticky=on manage=off
bspc rule --add Polybar \
    layer=above

exec $HOME/bin/init.sh &
sleep 2
([[ $(pidof -xs sxhkd) ]] && hkreload) || \
    sxhkd -c $XDG_CONFIG_HOME/sxhkd/sxhkdrc &

