#!/bin/sh

bspc monitor --reset-desktops I II III IV V VI VII VIII IX X

#++++++++++#
# Paddings #
#++++++++++#
bspc config top_padding		        2
bspc config bottom_padding          2
bspc config left_padding	        2
bspc config right_padding	        2

#++++++++++#
#  Colors  #
#++++++++++#
# color of a focused window of a focused monitor
bspc config focused_border_color    "#35C9BD"
# color of the preselected region
bspc config presel_feedback_color   "#35C9BD"
# color of an unfocused window
bspc config normal_border_color     "#6234C5"
# color of a focused window of an unfocused monitor
bspc config active_border_color     "#C16033"

#+++++++++++#
# Behaviors #
#+++++++++++#
bspc config border_width            2
bspc config window_gap		        6
bspc config split_ratio             0.50
bspc config automatic_scheme        spiral
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config pointer_follows_focus   true
bspc config pointer_follows_monitor true
bspc config initial_polarity        first_child
#bspc config initial_polarity       second_child

#++++++++++#
# Desktops #
#++++++++++#
bspc desktop '^3' --layout gapless_monocle
#bspc desktop '^7' --layout monocle

#++++++++++#
#  Rules   #
#++++++++++#
bspc rule --add netsurf \
    desktop='^3'
bspc rule --add Zathura	\
    desktop='IV' --one-shot follow=on focus=on state=fullscreen
bspc rule --add Conky \
    sticky=on manage=off lower=on


([[ $(pidof -xs sxhkd) ]] && hkreload) || \
    sxhkd -c $XDG_CONFIG_HOME/sxhkd/sxhkdrc &
$HOME/bin/autostart &

